### ISSUE TITLE
Stray `console.log` in 1.17.2 published on npmjs

### ISSUE THREAD

**Issue by adrukh** [LayeredStudio/whoiser#106]
**Version(s) affected**: 1.17.2

**Description**  
There's a leftover `console.log` call in `src/whoiser.js` on line 68 in the published 1.17.2 release on npmjs.com. I cannot find the release tag on this repo though.

**How to reproduce**  
Use 1.17.2 to make some whois calls, and you'll get a console.log printed for every call, made by this command:
```
console.log('whoisQuery', host, query)
```

**Possible Solution**  
Remove the line altogether :)

**Additional context**  
May I also suggest using some tool to align this repo's releases with those published on npmjs.com? :)

**Comment by gabemarshall** [comment]
This was driving me crazy today, thanks.

**Comment by AndreiIgna** [comment]
it is fixed in `v1.17.3`
