### ISSUE TITLE
.ch WHOIS not working

### ISSUE THREAD

**Issue by brunocrosier** [LayeredStudio/whoiser#15]
WHOIS queries for `.ch` domains always result in this response:

```javascript
{
whois.nic.ch: {
Domain Status: [ ],
Name Server: [ ],
text: [
"Requests of this client are not permitted. Please use https://www.nic.ch/whois/ for queries."
]
}
}
```

Is there an easy solution to this? Maybe hardcoding in the whois server for this domain ending?

**Comment by AndreiIgna** [comment]
Hi Bruno,

Haven't checked .ch domains until now, so didn't catch this. Thanks for reporting it.

If you know the WHOIS server that would work for this tld, it can be added in options like this:
`whoiser.domain('domain.ch', { host: 'new.whois.host' })`

When we find the correct WHOIS host, it can be added here in the library https://github.com/LayeredStudio/whoiser/blob/master/src/whoiser.js#L18

Today I'll check in more detail and see what I can find too

**Comment by brunocrosier** [comment]
thanks! I'm not sure but according to this page it looks like `whois.nic.ch` should work 
https://www.nic.ch/whois/domaincheck/#collapse-e745fb9f-4fef-11e6-b33a-525400a7a801-1

I will take a look today also 👍

**Comment by AndreiIgna** [comment]
Ah I see it, it's the port.
Default port for WHOIS is 43, but this server works with 4343

Will add the details here https://github.com/LayeredStudio/whoiser/blob/master/src/whoiser.js#L90 and publish a new release soon

**Comment by AndreiIgna** [comment]
Last answer was rushed, after quickly checking the page.. https://www.nic.ch/whois/domaincheck/#collapse-e745fb9f-4fef-11e6-b33a-525400a7a801-1

WHOIS server is disabled for .ch, and that registry offers WHOIS info only in the browser page. So it won't work through `whoiser` 😕

They do offer Domain Check, which is a different service. It shows only if the domain is registered or not, but no WHOIS info. You could use this to check domain availability, example here https://runkit.com/andreiigna/5efdeaa8e4f2d8001a00312d
