### ISSUE TITLE
Unable to parse Expire Date string with MomentJS

### ISSUE THREAD

**Issue by azakero** [LayeredStudio/whoiser#28]
Hello there. First of all, thank you so much for such an amazing package. 

Secondly, I'm facing an issue while trying to parse the Expiry Date to a readable format. Creation Date and Updated Date gets parsed smoothly without any problems. Based on [this](https://github.com/moment/moment/issues/1407), I'm assuming that the date string on Expiry Date is a **random string** and that is why it is showing 'Invalid Date' instead of the parsed date and a depcrecated warning in the terminal. 

I don't know if this is the right place to post this issue or in MomentJS but can you please take a look if date string of Expiry Date is actually a date string and not some random string with a date?

**Comment by AndreiIgna** [comment]
Hi @azakero, thanks, and hope this is useful for your projects.

About dates, this is still something that we can improve on.
At the moment, dates are not parsed or converted to a common format, so they may differ based on the WHOIS server used.
Some WHOIS servers use [ISO 8601 format](https://en.wikipedia.org/wiki/ISO_8601), some use a random format, so this package doesn't process it.
For which domain/tld do you see the error when using MomentJS?

A quick fix I noticed is that sometimes only the expiry date has an extra space at the end. In a project that also uses MomentJS, I do this `new Date(whois['Expiry Date'].trim())` and seems to work.

**Comment by azakero** [comment]
Thanks for the reply. I think I'm getting an error for .info domains. Also 'Last WHOIS data update' also doesn't provide a date as well for some queries. I'll give your solution a try and update here. Thanks again for this package.

**Comment by azakero** [comment]
Mate, that fix worked. Thanks a lot.
