### ISSUE TITLE
Unhandled WHOIS Response for .IT

### ISSUE THREAD

**Issue by JAD3N** [LayeredStudio/whoiser#44]
**Version(s) affected**: all?

**Description**  
The WHOIS server used for .IT returns an unhandled format that causes data such as contacts/registrar to be missed.

**How to reproduce** 
Use whoiser with any .IT TLD and compare it to the actual response.

**Additional context**  
The WHOIS response format used by **whois.nic.it**:
```
Registrar
  Organization:     Gandi SAS
  Name:             GANDI-REG
  Web:              http://www.gandi.net
  DNSSEC:           no
```

**Comment by JAD3N** [comment]
Here is also the structure for the nameservers:
```
Nameservers
  ns1.example.com
  ns2.example.com
```

**Comment by AndreiIgna** [comment]
Hey @JAD3N

The library has only a basic WHOIS parser, that handles the most common format `Label: value`.
`.it` (and many other ccTLDs) returns data in a different format, and this can't be parsed to JSON/object yet.

If you want to take a look at it, you can see how extra parsers were added here https://github.com/LayeredStudio/whoiser/blob/master/src/parsers.js#L265
This is something I also want to improve, and in the next few weeks I'll check which WHOIS server need custom parsers to add them.

**Comment by JAD3N** [comment]
@AndreiIgna I don't mind having a look into this to see if I can handle it. Would you be able to provide a list of WHOIS servers which have different formats that are already handled? That would give me a good head start.

**Comment by JAD3N** [comment]
@AndreiIgna

I've started re-implementing and documenting the different WHOIS response structures on a new branch:
https://github.com/JAD3N/whoiser/tree/formats

I'm planning on using a different parsing structure which you can find in this file:
https://github.com/JAD3N/whoiser/blob/formats/formats/default.md

This way I should be able to accommodate a variety of ccTLD responses.

Any feedback and suggestions would be appreciated.

**Comment by jonathansampson** [comment]
@JAD3N Check out https://github.com/LayeredStudio/whoiser/pull/92; it should improve the parsing of .it considerably.
