### ISSUE TITLE
getting error in domain search 

### ISSUE THREAD

**Issue by hamzaasad10** [LayeredStudio/whoiser#48]
{ 'whois.verisign-grs.com':
   { error: 'data.Name Server.map(...).flat is not a function' } } { 'whois.nic.google':
   { error: 'data.Name Server.map(...).flat is not a function' } }

getting this response each and every time 

let domainInfo2 = await whoiser.domain('google', {host: 'whois.nic.google', follow: 1})

**Comment by AndreiIgna** [comment]
hey @hamzaasad10,

this library uses `Array.flat` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat#browser_compatibility to process some WHOIS data, and that's a utility added in Node v11.

Is is possible to upgrade your NodeJS version? `whoiser` is being maintained and supports only the latest active NodeJS releases https://nodejs.org/en/about/releases/
