### ISSUE TITLE
List of TLDs

### ISSUE THREAD

**Issue by azakero** [LayeredStudio/whoiser#49]
Can you please provide the list of all TLDs that are currently supported? May be you can update the list as you include more TLDs?

**Comment by AndreiIgna** [comment]
hey @azakero,

All TLDs are supported 😀
WHOIS servers for a few TLDs are hardcoded in the library https://nodejs.org/en/about/releases/
and the rest are automatically retrieved from IANA server when needed:
- if no WHOIS server for a TLD is known https://github.com/LayeredStudio/whoiser/blob/master/src/whoiser.js#L81
- the library makes a request to `whois.iana.org` to request the WHOIS server for that TLD https://github.com/LayeredStudio/whoiser/blob/2f51c63337e11183ca752d83dd22cc7113c65d44/src/whoiser.js#L56
- this info is cached in memory and reused for subsequent calls for same TLDs

The full list can also be downloaded from here https://data.iana.org/TLD/tlds-alpha-by-domain.txt

Hope this helps
