### ISSUE TITLE
.US Domain Failing

### ISSUE THREAD

**Issue by jplandry908** [LayeredStudio/whoiser#58]
FYI - Querying '.us' domains started failing recently. I was able to fix this by adding a line in the **cacheTldWhoisServer** list for 'us'.

let cacheTldWhoisServer = {
	com: 'whois.verisign-grs.com',
	net: 'whois.verisign-grs.com',
	org: 'whois.pir.org',
	co: 'whois.nic.co',
	us: 'whois.nic.us',      **_<------ NEW LINE_**
	ai: 'whois.nic.ai',
	app: 'whois.nic.google',
	io: 'whois.nic.io',
	shop: 'whois.nic.shop',
	nyc: 'whois.nic.nyc',
}

**Comment by AndreiIgna** [comment]
hey @jplandry908,

Thanks for reporting this. The WHOIS server for .us is included in the library now
