### ISSUE TITLE
[Domain] Error with goo.gl next whois server string

### ISSUE THREAD

**Issue by AKorezin** [LayeredStudio/whoiser#6]
**Version(s) affected**: 1.6.5

**Description**  
goo.gl domain provides wrong information about next whois server:
```json5
'Registry WHOIS Server': ': whois.nic.gl'
```
Also [here](https://whois.nic.gl/)
```html
<tr><td>Registry WHOIS Server::&nbsp;</td><td>whois.nic.gl</td></tr>
```
So I get error:
```json5
': whois.nic.gl': { 
  'error': 'getaddrinfo ENOTFOUND : whois.nic.gl' 
}
```

**How to reproduce**  
```js
whoiser('goo.gl')
```
**Possible Solution**  
Use regexp to replace `::` with `:`
Or split by regexp `/(?::+)/`

**Additional context**  
https://github.com/LayeredStudio/whoiser/blob/b9e64942bb37509814ceeaedd71b5c47823fef32/src/whoiser.js#L20

**Comment by AndreiIgna** [comment]
hi @AKorezin thanks for reporting this. 

Indeed there's some WHOIS servers returning data in that format, and needs to be fixed. Didn't know it's the same for .gl, so good catch.

Should be resolved shorlty

**Comment by AndreiIgna** [comment]
Fixed in latest release @AKorezin, thanks for flagging this
