### ISSUE TITLE
How can I use it on next js client side?

### ISSUE THREAD

**Issue by neelhabib** [LayeredStudio/whoiser#73]
Unable to use it on client side / browser on next js.

```
 error - ./node_modules/whoiser/src/whoiser.js:1:0
Module not found: Can't resolve 'net'

Import trace for requested module:
./node_modules/whoiser/index.js
```

Is there any way to use it?

**Comment by AndreiIgna** [comment]
hey @neelhabib 

`whoiser` works only on a node environment, because it depends on [Node.js net](https://nodejs.org/api/net.html)
