### ISSUE TITLE
Umlauts not working for .de domains

### ISSUE THREAD

**Issue by lukasbableck** [LayeredStudio/whoiser#93]
**Version(s) affected**: 1.14.0

**Description**  
If you use an umlaut in a .de domain, you get 
`"Domain Status": [
    "invalid"
],`
This does work on other tlds and should also work on .de.

**How to reproduce**  
`whoiser.domain("testä.de")`

**Comment by jonathansampson** [comment]
The issue here is with the `punycode` step, occurring immediately within the `whoisDomain` function. Sending Unicode instead of ascii to whois.denic.de resolves the issue.

**Comment by AndreiIgna** [comment]
Thanks for the fix @jonathansampson, this is now merged and released in v1.15
